version: '3.9'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: abz
      POSTGRES_PASSWORD: abz
      POSTGRES_DB: abz
    ports:
      - '5432:5432'

  backend:
    build: .
    ports:
      - '8000:8000'
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_HOST: 'postgres'
